--2017-04-14 19:08:55--  https://raw.githubusercontent.com/jwillem/sem_ws2016_functional-programming_concurrency/master/paper/tex/IEEEtran.cls?token=AH18FAYqCBM4NC33pIukCJ2VYPoSGTWKks5Y-jxiwA%3D%3D
Resolving raw.githubusercontent.com... 151.101.12.133
Connecting to raw.githubusercontent.com|151.101.12.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 288304 (282K) [text/plain]
Saving to: ‘IEEEtran.cls?token=AH18FAYqCBM4NC33pIukCJ2VYPoSGTWKks5Y-jxiwA%3D%3D.1’

     0K .......... .......... .......... .......... .......... 17%  834K 0s
    50K .......... .......... .......... .......... .......... 35% 2.07M 0s
   100K .......... .......... .......... .......... .......... 53% 4.47M 0s
   150K .......... .......... .......... .......... .......... 71% 4.94M 0s
   200K .......... .......... .......... .......... .......... 88% 2.62M 0s
   250K .......... .......... .......... .                    100% 7.79M=0.1s

2017-04-14 19:08:55 (2.17 MB/s) - ‘IEEEtran.cls?token=AH18FAYqCBM4NC33pIukCJ2VYPoSGTWKks5Y-jxiwA%3D%3D.1’ saved [288304/288304]

